from bs4 import BeautifulSoup
import requests

start_url = 'http://bj.58.com/sale.shtml'
url_host = 'http://bj.58.com'

# =========================================== 获取到所有商品类别 ==========================================
def extract_channel(url):
    wb_data = requests.get(url)
    soup = BeautifulSoup(wb_data.text,'lxml')
    links = soup.select('#ymenu-side > ul > li > ul > li > span > a')
    for link in links:
        page_url = url_host + link.get('href')
        print(page_url)

extract_channel(start_url)

# ============================= 将得到的商品类别的列表直接赋值给python的列表变量 =============================
channel_list = '''
    http://bj.58.com/iphonesj/
    http://bj.58.com/sanxing/
    http://bj.58.com/nuojiya/
    http://bj.58.com/htc/
    http://bj.58.com/xiaomi/
    http://bj.58.com/ailixin/
    http://bj.58.com/zhongxingshouji/
    http://bj.58.com/lgsj/
    http://bj.58.com/kupaisj/
    http://bj.58.com/huaweisj/
    http://bj.58.com/lianxiang/
    http://bj.58.com/motuoluola/
    http://bj.58.com/heimei/
    http://bj.58.com/jinlisj/
    http://bj.58.com/meizu/
    http://bj.58.com/shoujipeijian/
    http://bj.58.com/quanqiutong/
    http://bj.58.com/ruyitong/
    http://bj.58.com/cdma/
    http://bj.58.com/tietong/
    http://bj.58.com/chonzhika/
    http://bj.58.com/shangwangshebei/
    http://bj.58.com/shoujiyewu/
    http://bj.58.com/xiaolingtong/
    http://bj.58.com/wanliang/
    http://bj.58.com/tabanmotuoche/
    http://bj.58.com/qishiche/
    http://bj.58.com/dapailiang/
    http://bj.58.com/yueyemotuoche/
    http://bj.58.com/yamaha/
    http://bj.58.com/bentianmoto/
    http://bj.58.com/jialing/
    http://bj.58.com/lingmumoto/
    http://bj.58.com/haojue/
    http://bj.58.com/qingqi/
    http://bj.58.com/zongshen/
    http://bj.58.com/putongzixingche/
    http://bj.58.com/zhediezixingche/
    http://bj.58.com/minizixingche/
    http://bj.58.com/gongluzixingche/
    http://bj.58.com/changdizixingche/
    http://bj.58.com/shandizixingche/
    http://bj.58.com/jieante/
    http://bj.58.com/meilida/
    http://bj.58.com/yongjiu/
    http://bj.58.com/fenghuangzxc/
    http://bj.58.com/feige/
    http://bj.58.com/jiema/
    http://bj.58.com/diandongzixingche/
    http://bj.58.com/diandongmotuoche/
    http://bj.58.com/zhediediandongche/
    http://bj.58.com/minidiandongche/
    http://bj.58.com/zhudongche/
    http://bj.58.com/jieanteddc/
    http://bj.58.com/aima/
    http://bj.58.com/xiaoniao/
    http://bj.58.com/qingqiddc/
    http://bj.58.com/lvyuanddc/
    http://bj.58.com/xinri/
    http://bj.58.com/jiaotasanlunche/
    http://bj.58.com/diandongsanlunche/
    http://bj.58.com/zhulisanlunche/
    http://bj.58.com/zixingchepeijian/
    http://bj.58.com/diandongchekongpeijian/
    http://bj.58.com/diandongchedianchi/
    http://bj.58.com/xiuchegongju/
    http://bj.58.com/qixingzhuangbei/
    http://bj.58.com/taishiji/
    http://bj.58.com/fuwuqi/
    http://bj.58.com/ibm/
    http://bj.58.com/lenovo/
    http://bj.58.com/apple/
    http://bj.58.com/dell/
    http://bj.58.com/asus/
    http://bj.58.com/compaq/
    http://bj.58.com/sony/
    http://bj.58.com/samsung/
    http://bj.58.com/pbdnipad/
    http://bj.58.com/pbdnsanxing/
    http://bj.58.com/pbdnlianxiang/
    http://bj.58.com/pbdnaiguozhe/
    http://bj.58.com/wangka/
    http://bj.58.com/xianshiqi/
    http://bj.58.com/cpu/
    http://bj.58.com/xianka/
    http://bj.58.com/zhuban/
    http://bj.58.com/yingpan/
    http://bj.58.com/ydyingpan/
    http://bj.58.com/zhoubianshebei/pve_5620_398628/
    http://bj.58.com/bujianduandianyuan/
    http://bj.58.com/shubiao/
    http://bj.58.com/shexiangtou/
    http://bj.58.com/usb/
    http://bj.58.com/smqita/pve_5623_398637/
    http://bj.58.com/smqita/pve_5623_398636/
    http://bj.58.com/smqita/
    http://bj.58.com/danfanxiangji/
    http://bj.58.com/kapianxiangji/
    http://bj.58.com/weidanxiangji/
    http://bj.58.com/jingtou/
    http://bj.58.com/xiangjipeijian/
    http://bj.58.com/qitaxiangji/
    http://bj.58.com/ipod/
    http://bj.58.com/mpsantouch/
    http://bj.58.com/mpsannano/
    http://bj.58.com/mpsan/
    http://bj.58.com/mpsi/
    http://bj.58.com/psp/
    http://bj.58.com/yxjpsv/
    http://bj.58.com/yxjnds/
    http://bj.58.com/yxjxbox/
    http://bj.58.com/yxjpssan/
    http://bj.58.com/yxjpser/
    http://bj.58.com/yxjwii/
    http://bj.58.com/yingyinjiadian/
    http://bj.58.com/shenghuojiadian/
    http://bj.58.com/chuweijiadian/
    http://bj.58.com/jiadianpeijian/
    http://bj.58.com/yjcaidian/
    http://bj.58.com/gqcaidian/
    http://bj.58.com/dlzcaidian/
    http://bj.58.com/biguakt/
    http://bj.58.com/guishikt/
    http://bj.58.com/zhongyangkt/
    http://bj.58.com/quanzidongxiyiji/
    http://bj.58.com/guntongxiyiji/
    http://bj.58.com/shuanggangxiyiji/
    http://bj.58.com/minixiyiji/
    http://bj.58.com/shuangkaimenbx/
    http://bj.58.com/duikaimenbx/
    http://bj.58.com/minibx/
    http://bj.58.com/lishibg/
    http://bj.58.com/wohibg/
    http://bj.58.com/zhanshibg/
    http://bj.58.com/danrenchuang/
    http://bj.58.com/shuanrenchuang/
    http://bj.58.com/chuangcengchuang/
    http://bj.58.com/zhediechuang/
    http://bj.58.com/tongchuang/
    http://bj.58.com/chuangdian/
    http://bj.58.com/guizi/
    http://bj.58.com/zhuolei/
    http://bj.58.com/zuoju/
    http://bj.58.com/jiajushafa/
    http://bj.58.com/chaji/
    http://bj.58.com/jujia/
    http://bj.58.com/saomiaoyi/
    http://bj.58.com/yitiji/
    http://bj.58.com/chuanzhenji/
    http://bj.58.com/touyingji/
    http://bj.58.com/fuyinji/
    http://bj.58.com/dayinji/
    http://bj.58.com/tanfen/
    http://bj.58.com/mohemoshui/
    http://bj.58.com/wenjiangui/
    http://bj.58.com/huiyizhuo/
    http://bj.58.com/baoxiangui/
    http://bj.58.com/bangongzhuoyi/
    http://bj.58.com/bangongyi/
    http://bj.58.com/bangongjiaju/pve_5733_398638/
    http://bj.58.com/bangongjiaju/pve_5733_398639/
    http://bj.58.com/huagong/
    http://bj.58.com/fangzhi/
    http://bj.58.com/fyinshua/
    http://bj.58.com/gongcheng/
    http://bj.58.com/zaozhi/
    http://bj.58.com/kuangye/
    http://bj.58.com/mugongshebei/
    http://bj.58.com/diandongji/
    http://bj.58.com/nongye/
    http://bj.58.com/muyingzaojiao/
    http://bj.58.com/ertongyongpin/
    http://bj.58.com/zhiniaoku/
    http://bj.58.com/yongpinlalaku/
    http://bj.58.com/yongpinbeidai/
    http://bj.58.com/yongpinxuebudai/
    http://bj.58.com/yongpinyouxidai/
    http://bj.58.com/yongpinjianshenjia/
    http://bj.58.com/yongpinshuidai/
    http://bj.58.com/naifen/
    http://bj.58.com/weiyangfushi/
    http://bj.58.com/weiyangyingyangpin/
    http://bj.58.com/weiyangnaiping/
    http://bj.58.com/weiyangnaizui/
    http://bj.58.com/weiyangxinaiqi/
    http://bj.58.com/weiyangnuannaiqi/
    http://bj.58.com/yingerchuang/
    http://bj.58.com/yingerche/
    http://bj.58.com/tongchexuebu/
    http://bj.58.com/tongcheyaoyi/
    http://bj.58.com/tongzuoyi/
    http://bj.58.com/tongcanyi/
    http://bj.58.com/tongniuche/
    http://bj.58.com/tongzixingche/
    http://bj.58.com/tongsanlunche/
    http://bj.58.com/yongpintaixin/
    http://bj.58.com/fangfusefu/
    http://bj.58.com/mmfuzhuang/
    http://bj.58.com/yongpinshoufu/
    http://bj.58.com/yongpinyunfuzhen/
    http://bj.58.com/fushipeijian/
    http://bj.58.com/fuzhuangshoushi/
    http://bj.58.com/fuzhuangshoubiao/
    http://bj.58.com/fuzhuangtxue/
    http://bj.58.com/fuzhuangchenshan/
    http://bj.58.com/fuzhuangwaitao/
    http://bj.58.com/fuzhuangkuzi/
    http://bj.58.com/qunzifs/
    http://bj.58.com/fuzhuangxizhuang/
    http://bj.58.com/tongzhuang/
    http://bj.58.com/xiuxianxie/
    http://bj.58.com/yundongxie/
    http://bj.58.com/fanbuxie/
    http://bj.58.com/gaogenxie/
    http://bj.58.com/xiebanxi/
    http://bj.58.com/pixie/
    http://bj.58.com/xiangbaodanjian/
    http://bj.58.com/xiangbaoshuangjian/
    http://bj.58.com/xiangbaoshubao/
    http://bj.58.com/xiangbaoqianbao/
    http://bj.58.com/xiangbaolagan/
    http://bj.58.com/xiangbaodiannao/
    http://bj.58.com/meirongyongpin/
    http://bj.58.com/hufu/
    http://bj.58.com/meirongmeiti/
    http://bj.58.com/caizhuang/
    http://bj.58.com/baojianshipin/
    http://bj.58.com/meifa/
    http://bj.58.com/xiangshuimr/
    http://bj.58.com/gudongguwan/
    http://bj.58.com/mingxingwupin/
    http://bj.58.com/shufa/
    http://bj.58.com/shanshuihua/
    http://bj.58.com/renwuhua/
    http://bj.58.com/huaniaohua/
    http://bj.58.com/zhuangshihua/
    http://bj.58.com/guijinshu/
    http://bj.58.com/zhubaoshshi/
    http://bj.58.com/fangjinshshi/
    http://bj.58.com/zhubaoshipin/pve_5731_398646/
    http://bj.58.com/zhubaoshipin/pve_5731_398647/
    http://bj.58.com/youpiaoyoupin/
    http://bj.58.com/fanggujiaju/
    http://bj.58.com/aoyunjinianbi/
    http://bj.58.com/sbjinianpin/
    http://bj.58.com/cddvd/
    http://bj.58.com/yingpandianshiju/
    http://bj.58.com/ruanjiants/
    http://bj.58.com/jishulei/
    http://bj.58.com/gongjushu/
    http://bj.58.com/kaoshi/
    http://bj.58.com/shenghuolei/
    http://bj.58.com/xiaoshuo/
    http://bj.58.com/youyongwt/
    http://bj.58.com/yujiawt/
    http://bj.58.com/diaoyuyongju/
    http://bj.58.com/qipai/
    http://bj.58.com/yundongfushi/pve_5728_398644/
    http://bj.58.com/yundongfushi/pve_5728_398648/
    http://bj.58.com/tabuji/
    http://bj.58.com/peobuji/
    http://bj.58.com/anmoyi/
    http://bj.58.com/liubinghuaban/
    http://bj.58.com/jianshenche/
    http://bj.58.com/xueshwenju/
    http://bj.58.com/jiaoxueyj/
    http://bj.58.com/taiqiuzhuo/
    http://bj.58.com/wangqiuyongpin/
    http://bj.58.com/zuqiuwt/
    http://bj.58.com/pingpangqiuwt/
    http://bj.58.com/yumaoqiuwt/
    http://bj.58.com/lanqiutw/
    http://bj.58.com/jita/
    http://bj.58.com/gangqin/
    http://bj.58.com/dianziqin/
    http://bj.58.com/shoufengqing/
    http://bj.58.com/erhuwt/
    http://bj.58.com/yintundaomo/
    http://bj.58.com/xingwanou/
    http://bj.58.com/jiandanbianxie/
    http://bj.58.com/nanyongchuandai/
    http://bj.58.com/fangzhenrufang/
    http://bj.58.com/zhendongbang/
    http://bj.58.com/yindiciji/
    http://bj.58.com/gdianhouting/
    http://bj.58.com/tiaodan/
    http://bj.58.com/fengrutiaodou/
    http://bj.58.com/jiqingyongju/
    http://bj.58.com/qingqutiaosao/
    http://bj.58.com/lingleiwanju/
    http://bj.58.com/yanshitaohuan/
    http://bj.58.com/tiaoqingxiangshui/
    http://bj.58.com/zhifuyouhuo/
    http://bj.58.com/dingziku/
    http://bj.58.com/siwameitui/
    http://bj.58.com/nanshineiyi/
    http://bj.58.com/runhuaji/
    http://bj.58.com/aqyp/
    http://bj.58.com/anquantao/
    http://bj.58.com/qitachengren/
    http://bj.58.com/xiaoyuan/pve_5536_1/
    http://bj.58.com/xiaoyuan/pve_5536_2/
    http://bj.58.com/xiaoyuan/pve_5536_3/
    http://bj.58.com/xiaoyuan/pve_5536_4/
    http://bj.58.com/xiaoyuan/pve_5536_5/
    http://bj.58.com/esqgjiaju/
    http://bj.58.com/esqgfuzhuang/
    http://bj.58.com/esqgtushu/
    http://bj.58.com/ershouqiugou/
    http://bj.58.com/wangyou/
    http://bj.58.com/huanwu/
    http://bj.58.com/lipin/
    http://bj.58.com/wuyuanwupin/
    http://bj.58.com/fuwujy/
    http://bj.58.com/canjirenyongpin/
    http://bj.58.com/weixing/
    http://bj.58.com/qitatiaozao/
'''