# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-06 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='got_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='waterfall',
            name='like_num',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
