# Generated by Django 2.0.3 on 2018-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='create_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.FloatField(default=1.1),
        ),
    ]
